# Use container-based infrastructure
sudo: false
language: scala
jdk: oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/ba78da55d38be475094d
    on_success: change
    on_failure: always
    on_start: never
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
